---

# AB: the name of the VG used as the pool for KVM volumes.
makevolume_vg: '{% if preparekvm_vg_info is defined %}{{ preparekvm_vg_info.stdout|default("")}}{% else %}{% endif %}'

# AB: the size of the system disk volume. Default is set to
# 4 GiB because for a minimal install it provides sufficient
# space. For value specification see section "NOTES" of
# virsh(1). So g == G == GiB.
makevolume_size: 4g
