---

# AB: the ISO and software are located in a certain
# directory. The default value is set here.
kickstartinstall_clone_vm_dir: '{{create_tpl_vm_dir|default("~/clone_vm")}}'

# AB: the glob pattern is consumed by the shell, so it must
# adhere to the fnmatch(3) rules.
kickstartinstall_iso_pattern: '*-x86_64-Minimal-*.iso'

# AB: the name of the VG used as the pool for KVM volumes.
kickstartinstall_vg: '{% if preparekvm_vg_info is defined %}{{ preparekvm_vg_info.stdout|default("")}}{% else %}{% endif %}'
